---
# - include_tasks: install.yml
# - name: Install hyperland
#   ansible.builtin.yay:
#     name: hyperland
#     state: present

- name: Copy the config folder
  template:
    src: "templates/config/hypr/"
    dest: "{{ ansible_env.HOME }}/.config/hypr/"
    force: yes
