---
# - include_tasks: install.yml
# - name: Install hyperland
#   ansible.builtin.yay:
#     name: hyperland
#     state: present

- name : install dependency
  pacman: 
    name: "{{ item }}"
    state: present
  loop:
    - rsync
  become: yes

- name: Copy the config folder {{ ansible_env.HOME }}
  synchronize:
    src: "files/config/"
    dest: "{{ ansible_env.HOME }}/.config/"
    delete: yes
    recursive: yes

