---
# - include_tasks: install.yml
# - name: Install hyperland
#   ansible.builtin.yay:
#     name: hyperland
#     state: present

- name: Copy the config folder
  copy:
    src: "files/config/"
    dest: "{{ ansible_env.HOME }}/.config/hypr/"
    # force: yes

