---
# - include_tasks: install.yml
# - name: Install hyperland
#   ansible.builtin.yay:
#     name: hyperland
#     state: present

- name: Copy the config folder {{ ansible_env.HOME }}
  synchronize:
    src: "files/config/hypr/"
    dest: "{{ ansible_env.HOME }}/.config/hypr/"
    delete: yes
    recursive: yes

