---
- name : install kitty 
  pacman:
    name: kitty 
    state: present
  become: true

- name: Copy the config folder
  ansible.builtin.copy:
    src: "templates/config/kitty/"
    dest: "{{ ansible_env.HOME }}/.config/kitty/"

