---
- name: install rofi
  pacman:
    name: rofi
    state: present
  become: true

- name: Copy the config folder
  synchronize:
    src: "files/config/rofi/"
    dest: "{{ ansible_env.HOME }}/.config/rofi/"
    delete: yes
    recursive: yes

