---
- name: install waybar 
  pacman:
    name: waybar 
    state: present
  become: yes

- name: Copy the config folder {{ ansible_env.HOME }}
  synchronize:
    src: "files/config/waybar/"
    dest: "{{ ansible_env.HOME }}/.config/waybar/"
    delete: yes
    recursive: yes

