---

- name: update package
  pacman: 
    update_cache: yes
    upgrade: yes
  become: true

- name: install pacman dependecy 
  pacman: 
    name: "{{ item }}"
    state: present
  loop:
    - rsync
    - git
    - ttf-hack 
    - ttf-nerd-fonts-symbols
  become: true

